version: '3.8'

services:
  # redis:
  #   image: redis:6.2
  #   command: redis-server --requirepass your_redis_password
  #   restart: unless-stopped
  #   ports:
  #     - '6389:6379'
  #   volumes:
  #     - redis_data:/data

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./components/backend/.env
    ports:
      - "5482:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные в volume



  # backend:
  #   build: ./components/backend
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - ./components/backend/.env
  #   depends_on:
  #     - redis
  #     - vault

volumes:
  # redis_data:
  postgres_data:
